# Generated by Django 2.2.6 on 2019-12-18 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 6, 47, 10, 608251, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
